### ISSUE TITLE
容器资源状态获取异常 `NaN undefined / NaN undefined (0%)`

### ISSUE THREAD

**Issue by devnakx** [lisaac/luci-app-dockerman#175]
**问题描述**
![image](https://github.com/lisaac/luci-app-dockerman/assets/38558065/752c2449-d53f-4835-83a2-8d095d15e098)
和这个问题一样 #163
重启或者重刷固件都无用

**版本信息:**
 - openwrt 版本：built from [lede](https://github.com/coolsnowwolf/lede) with latest source code
 - luci 版本：18.06 LuCI Master (git-23.289.72135-4b5740c)
 - docker daemon 版本：24.0.5
 - dockerman 版本：v0.5.26-1 from [luci](https://github.com/coolsnowwolf/luci)

**Comment by lisaac** [comment]
请提供下是什么镜像？

**Comment by devnakx** [comment]
> 请提供下是什么镜像？

容器镜像吗？但我这不是只有一个容器或者某个镜像出了问题，而是所有容器点进去查看都无法获取资源状态

**Comment by devnakx** [comment]
我自己翻了下也没看到任何可能和这个问题相关的日志，我也不好判断这个到底是什么原因了

**Comment by devnakx** [comment]
因为docker和容器啥的都是运行正常的，就只是获取不到这个资源状态

**Comment by devnakx** [comment]
系统日志里找了两段可能相关的日志，其它真找不出有啥相关了
```
Tue Oct 17 16:20:07 2023 daemon.err uhttpd[2163]: sh: /etc/init.d/dockerd: line 6: extra_command: not found
Tue Oct 17 16:20:07 2023 daemon.err uhttpd[2163]: sh: /etc/init.d/dockerd: line 7: extra_command: not found
Tue Oct 17 16:20:07 2023 daemon.err uhttpd[2163]: sh: /etc/init.d/dockerman: line 6: config_load: not found
Tue Oct 17 16:20:07 2023 daemon.err uhttpd[2163]: sh: /etc/init.d/dockerman: line 130: extra_command: not found
Tue Oct 17 16:20:07 2023 daemon.err uhttpd[2163]: sh: /etc/init.d/dockerman: line 131: extra_command: not found
```
```
Tue Oct 17 16:31:34 2023 daemon.err modprobe: failed to find a module named aufs
Tue Oct 17 16:31:34 2023 daemon.err dockerd[22024]: time="2023-10-17T08:31:34.748541841Z" level=error msg="post event" error="failed to connect: dial unix /var/run/docker/containerd/containerd.sock.ttrpc: connect: connection refused"
Tue Oct 17 16:31:44 2023 daemon.info modprobe: nf_conntrack is already loaded
Tue Oct 17 16:31:44 2023 daemon.err modprobe: failed to find a module named nf_conntrack_netlink
```

**Comment by lisaac** [comment]
运行一下，看看结果
```
docker top [container_id]
docker stats [container_id] --no-stream
```

**Comment by devnakx** [comment]
```
root@OpenWRT:~# docker top smartdns
PID                 USER                VSZ                 STAT                COMMAND
30951               root                27092               S                   /usr/sbin/smartdns -f -x -p -
root@OpenWRT:~# docker stats smartdns --no-stream
CONTAINER ID   NAME       CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
90fde66819c1   smartdns   0.00%     0B / 0B             0.00%     0B / 0B   0B / 0B     0
```
`docker stats`好像也是无法获取，这个可能是哪些原因？

**Comment by lisaac** [comment]
先使用这个脚本查一下内核模块
https://github.com/lisaac/luci-app-dockerman/issues/36#issuecomment-612375880

**Comment by devnakx** [comment]
`docker info`信息如下：
```
root@OpenWRT:~# docker info
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.56
 Operating System: OpenWrt SNAPSHOT
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.849GiB
 Name: OpenWRT
 ID: 1bcdc349-5905-4211-977d-e0574f24767f
 Docker Root Dir: /opt/docker
 Debug Mode: false
 Username: devioa
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by devnakx** [comment]
> 先使用这个脚本查一下内核模块 [#36 (comment)](https://github.com/lisaac/luci-app-dockerman/issues/36#issuecomment-612375880)

好的我试试

**Comment by devnakx** [comment]
好像找不到 kernel config
```
root@OpenWRT:~# ./check-config.sh
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
error: cannot find kernel config
  try running this script again, specifying the kernel config:
    CONFIG=/path/to/kernel/.config ./check-config.sh or ./check-config.sh /path/to/kernel/.config
```

**Comment by lisaac** [comment]
从`docker info`结果来看，环境应该是有点问题的
`containerd version` 和 `runc version` 都没有显示，可能与此有关

至于`kernel config`，你使用的是哪个版本的 openwrt，编译时的`.config`是否还在？

**Comment by lisaac** [comment]
也可以尝试检查一下，系统是否有 containerd 和 runc

**Comment by devnakx** [comment]
> 也可以尝试检查一下，系统是否有 containerd 和 runc

有的
```
root@OpenWRT:~# opkg list|grep containerd
containerd - 1.7.1-1
root@OpenWRT:~# opkg list|grep runc
runc - 1.1.8-1
```

> 从`docker info`结果来看，环境应该是有点问题的 `containerd version` 和 `runc version` 都没有显示，可能与此有关

我看我 WSL2 上 Ubuntu 的`docker info`打印出来也没有这两个的版本信息：
```
devioa@Devioa-Desktop:~$ docker info
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /home/devioa/.docker/cli-plugins/docker-buildx

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 27
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 15.58GiB
 Name: Devioa-Desktop
 ID: a2e91ce2-9afd-4711-943b-29fc581d002f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: devioa
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

> 至于`kernel config`，你使用的是哪个版本的 openwrt，编译时的`.config`是否还在？

在的，7000+行不好直接贴上来，我传我 alist 上了，http://mosol.oicp.net:5244/d/Assets/.config

**Comment by lisaac** [comment]
> 在的，7000+行不好直接贴上来，我传我 alist 上了，http://mosol.oicp.net:5244/d/Assets/.config

下面是用 `check config` 结果：

```
Generally Necessary:
- cgroup hierarchy: cgroupv2
  Controllers:
  - cpu: available
  - cpuset: available
  - io: available
  - memory: available
  - pids: available
- apparmor: enabled, but apparmor_parser missing
    (use "apt-get install apparmor" to fix this)
- CONFIG_NAMESPACES: missing
- CONFIG_NET_NS: missing
- CONFIG_PID_NS: missing
- CONFIG_IPC_NS: missing
- CONFIG_UTS_NS: missing
- CONFIG_CGROUPS: missing
- CONFIG_CGROUP_CPUACCT: missing
- CONFIG_CGROUP_DEVICE: missing
- CONFIG_CGROUP_FREEZER: missing
- CONFIG_CGROUP_SCHED: missing
- CONFIG_CPUSETS: missing
- CONFIG_MEMCG: missing
- CONFIG_KEYS: missing
- CONFIG_VETH: missing
- CONFIG_BRIDGE: missing
- CONFIG_BRIDGE_NETFILTER: missing
- CONFIG_IP_NF_FILTER: missing
- CONFIG_IP_NF_TARGET_MASQUERADE: missing
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: missing
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: missing
- CONFIG_NETFILTER_XT_MATCH_IPVS: missing
- CONFIG_NETFILTER_XT_MARK: missing
- CONFIG_IP_NF_NAT: missing
- CONFIG_NF_NAT: missing
- CONFIG_POSIX_MQUEUE: missing
- CONFIG_CGROUP_BPF: missing

Optional Features:
- CONFIG_USER_NS: missing
- CONFIG_SECCOMP: enabled
- CONFIG_SECCOMP_FILTER: missing
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_SWAP: missing
    (cgroup swap accounting is currently enabled)
- CONFIG_BLK_CGROUP: missing
- CONFIG_BLK_DEV_THROTTLING: missing
- CONFIG_CGROUP_PERF: missing
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: missing
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: missing
- CONFIG_FAIR_GROUP_SCHED: missing
- CONFIG_IP_NF_TARGET_REDIRECT: missing
- CONFIG_IP_VS: missing
- CONFIG_IP_VS_NFCT: missing
- CONFIG_IP_VS_PROTO_TCP: missing
- CONFIG_IP_VS_PROTO_UDP: missing
- CONFIG_IP_VS_RR: missing
- CONFIG_SECURITY_SELINUX: missing
- CONFIG_SECURITY_APPARMOR: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: missing
- CONFIG_EXT4_FS_POSIX_ACL: missing
- CONFIG_EXT4_FS_SECURITY: missing
    enable these ext4 configs if you are using ext4 as backing filesystem
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: missing
    - CONFIG_BRIDGE_VLAN_FILTERING: missing
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: missing
      - CONFIG_CRYPTO_AEAD: missing
      - CONFIG_CRYPTO_GCM: missing
      - CONFIG_CRYPTO_SEQIV: missing
      - CONFIG_CRYPTO_GHASH: missing
      - CONFIG_XFRM: missing
      - CONFIG_XFRM_USER: missing
      - CONFIG_XFRM_ALGO: missing
      - CONFIG_INET_ESP: missing
      - CONFIG_NETFILTER_XT_MATCH_BPF: missing
  - "ipvlan":
    - CONFIG_IPVLAN: missing
  - "macvlan":
    - CONFIG_MACVLAN: missing
    - CONFIG_DUMMY: missing
  - "ftp,tftp client in container":
    - CONFIG_NF_NAT_FTP: missing
    - CONFIG_NF_CONNTRACK_FTP: missing
    - CONFIG_NF_NAT_TFTP: missing
    - CONFIG_NF_CONNTRACK_TFTP: missing
- Storage Drivers:
  - "btrfs":
    - CONFIG_BTRFS_FS: missing
    - CONFIG_BTRFS_FS_POSIX_ACL: missing
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
  - "zfs":
    - /dev/zfs: present
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

```

**Comment by devnakx** [comment]
啊这，全都 missing 啊？可我在 .config 里搜索一些关键词（比如`NET_NS`）看了都是`y`呀，请问您知道可能是什么原因呢？这个真触及我知识盲区了😨

**Comment by lisaac** [comment]
> 啊这，全都 missing 啊？可我在 .config 里搜索一些关键词（比如`NET_NS`）看了都是`y`呀，请问您知道可能是什么原因呢？这个真触及我知识盲区了😨

可能是需要 `.kernel_config` 文件来检查，当然你可直接检查一下这些内核模块是否都配置了

**Comment by devnakx** [comment]
> 可能是需要 `.kernel_config` 文件来检查，当然你可直接检查一下这些内核模块是否都配置了

这个文件我在哪儿可以找到？

**Comment by lisaac** [comment]
没记错 openwrt 编译目录能找到

**Comment by devnakx** [comment]
我在`lede`目录下搜索没有找到`.kernel_config`
我手动翻了下，只在`lede/config`里找到一个很相似的`Config-kernel.in`
内容大概是这样的：
```
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2006-2014 OpenWrt.org

config KERNEL_BUILD_USER
	string "Custom Kernel Build User Name"
	default "builder" if BUILDBOT
	default ""
	help
	  Sets the Kernel build user string, which for example will be returned
	  by 'uname -a' on running systems.
	  If not set, uses system user at build time.

config KERNEL_BUILD_DOMAIN
	string "Custom Kernel Build Domain Name"
	default "buildhost" if BUILDBOT
	default ""
	help
	  Sets the Kernel build domain string, which for example will be
	  returned by 'uname -a' on running systems.
	  If not set, uses system hostname at build time.

config KERNEL_PRINTK
	bool "Enable support for printk"
	default y

config KERNEL_SWAP
	bool "Support for paging of anonymous memory (swap)"
	default y if !SMALL_FLASH

config KERNEL_PROC_STRIPPED
	bool "Strip non-essential /proc functionality to reduce code size"
	default y if SMALL_FLASH

config KERNEL_DEBUG_FS
	bool "Compile the kernel with debug filesystem enabled"
	default y
	help
	  debugfs is a virtual file system that kernel developers use to put
	  debugging files into. Enable this option to be able to read and
	  write to these files. Many common debugging facilities, such as
	  ftrace, require the existence of debugfs.

config KERNEL_MIPS_FP_SUPPORT
	bool
	default y if TARGET_pistachio

config KERNEL_ARM_PMU
	bool
	default n
	depends on (arm || aarch64)
......
```

**Comment by lisaac** [comment]
@devioa 
```
Generally Necessary:
- cgroup hierarchy: cgroupv2
  Controllers:
  - cpu: available
  - cpuset: available
  - io: available
  - memory: available
  - pids: available
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: missing
- CONFIG_CGROUP_FREEZER: missing
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: missing
- CONFIG_BRIDGE: missing
- CONFIG_BRIDGE_NETFILTER: missing
- CONFIG_IP_NF_FILTER: missing
- CONFIG_IP_NF_TARGET_MASQUERADE: missing
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: missing
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: missing
- CONFIG_NETFILTER_XT_MATCH_IPVS: missing
- CONFIG_NETFILTER_XT_MARK: missing
- CONFIG_IP_NF_NAT: missing
- CONFIG_NF_NAT: missing
- CONFIG_POSIX_MQUEUE: enabled
- CONFIG_CGROUP_BPF: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_SECCOMP_FILTER: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_MEMCG_SWAP: enabled
    (cgroup swap accounting is currently enabled)
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: missing
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: missing
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_IP_NF_TARGET_REDIRECT: missing
- CONFIG_IP_VS: missing
- CONFIG_IP_VS_NFCT: missing
- CONFIG_IP_VS_PROTO_TCP: missing
- CONFIG_IP_VS_PROTO_UDP: missing
- CONFIG_IP_VS_RR: missing
- CONFIG_SECURITY_SELINUX: missing
- CONFIG_SECURITY_APPARMOR: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: missing
- CONFIG_EXT4_FS_POSIX_ACL: missing
- CONFIG_EXT4_FS_SECURITY: missing
    enable these ext4 configs if you are using ext4 as backing filesystem
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: missing
    - CONFIG_BRIDGE_VLAN_FILTERING: missing
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: missing
      - CONFIG_CRYPTO_AEAD: missing
      - CONFIG_CRYPTO_GCM: missing
      - CONFIG_CRYPTO_SEQIV: missing
      - CONFIG_CRYPTO_GHASH: missing
      - CONFIG_XFRM: missing
      - CONFIG_XFRM_USER: missing
      - CONFIG_XFRM_ALGO: missing
      - CONFIG_INET_ESP: missing
      - CONFIG_NETFILTER_XT_MATCH_BPF: missing
  - "ipvlan":
    - CONFIG_IPVLAN: missing
  - "macvlan":
    - CONFIG_MACVLAN: missing
    - CONFIG_DUMMY: missing
  - "ftp,tftp client in container":
    - CONFIG_NF_NAT_FTP: missing
    - CONFIG_NF_CONNTRACK_FTP: missing
    - CONFIG_NF_NAT_TFTP: missing
    - CONFIG_NF_CONNTRACK_TFTP: missing
- Storage Drivers:
  - "btrfs":
    - CONFIG_BTRFS_FS: missing
    - CONFIG_BTRFS_FS_POSIX_ACL: missing
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
  - "zfs":
    - /dev/zfs: present
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000
```
